services:
  - type: web
    name: random-chat
    env: node
    buildCommand: npm install --include=dev && npm install --prefix client --include=dev && npm run build --prefix client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
