services:
  # Web Service for the app
  - type: web
    name: random-chat
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
